#!/usr/bin/env ruby

fileNames = `git log -1 --oneline`.split("\n")
logFound = false

puts fileNames
fileNames.each do |fileName|
    
    if fileName =~ /[ref :]/
        puts "Commit done !"
	# file = File.open(fileName)
	# content = file.read
	#if logRegex.match(content)
		#logFound = true
		#puts "|POLICY| console.log() found in file : #{fileName}"
    else
        puts "|POLICY| Commit refused, please add the ticket reference ex: [ref : 42]"
	    exit 1
	end
end
